# Generated by Django 4.1.4 on 2023-02-22 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edugamesapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='date',
            field=models.DateField(default='1999-12-23'),
            preserve_default=False,
        ),
    ]
